### ISSUE TITLE
cloudflare-worker does not return value.

### ISSUE THREAD

**Issue by shiyuhang0** [brettscott/cloudflare-worker-tunnel-mysql-example#1]
I try to use TiDB, a MySQL-compatible database to replace MySQL.
I do find the SQL has been executed in the TiDB server. But find the result is still empty `{"result":[]}` when I fetch data from worker.

I have also tried the official mysql-worker. it returns the same result. I think it is not an issue of TiDB because TiDB can work with most of the MySQL drivers including the [mysql2](https://www.npmjs.com/package/mysql2)

I think it may because `cloudflare-worker-tunnel-mysql-example` does not handle some packages correctly.

Could you please give me some advice? or how can I debug the worker, I find it hard to known where is the problems :(

**Comment by brettscott** [comment]
@shiyuhang0 Have you tried executing the query directly on TiDB CLI or MySQL Workbench?  The query being executed in both repos is: “SELECT 42”. 

Have you tried a different query which is likely to return a record?

**Comment by shiyuhang0** [comment]
Thank you for your reply. I think I miss some information. it works with MySQL but can't work with TiDB.

I have test`SELECT 42` in TiDB, it returns 42. I have also test other queries but the result are still empty. Here is a [reference](https://docs.pingcap.com/tidb/stable/quick-start-with-tidb) of how to build a TiDB in 3 minute if you need.

TiDB is fully compatible with the mysql protocol, and it works with most of the MySQL driver. I think cloudflare-worker-tunnel-mysql-example may does not handle some packages correctly. But I fail to find the bug :(

besides, cloudflare-worker-tunnel-mysql-example looks can't deal with TLS connection, I didn't see it handle the TLS package.

Maybe a stupid question: why can't worker use MySQL driver, like [mysql2](https://www.npmjs.com/package/mysql2)

**Comment by brettscott** [comment]
> why can't worker use MySQL driver, like mysql2

Cloudflare workers are not built on top of Node, instead directly on top of V8 engine.

**Comment by shiyuhang0** [comment]
I have found the implement of mysql driver may copy from [deno mysql driver](https://github.com/denodrivers/mysql).

And I reproduce the problem with it
- 3306 : MySQL
- 4000: TiDB

![fbJDDRmXF9](https://user-images.githubusercontent.com/52435083/203385018-d4f51d1f-261c-41ba-84ac-f12e47166232.jpg)
![de6fb202-ab07-4f45-8856-9e50180b0bfc](https://user-images.githubusercontent.com/52435083/203385060-f3e425ec-2c85-4e4a-b7b0-a032b78ec645.jpeg)


deno mysql driver seems not support tls too. Maybe we can find a better one to replace it.

**Comment by shiyuhang0** [comment]
Closed by https://github.com/denodrivers/mysql/issues/136

**Comment by brettscott** [comment]
@shiyuhang0 great work. Thanks for providing an update!  I’ll take a look at the deno driver.
