### ISSUE TITLE
Similar Solution Viable For MSSQL?

### ISSUE THREAD

**Issue by mark-mybaggage** [brettscott/cloudflare-worker-tunnel-mysql-example#3]
I understand this is for MySQL, however could this approach also work for MSSQL?

**Comment by brettscott** [comment]
Yes, this approach could work the same way with MSSQL.

You'll need to ensure the following headers are sent when you establish a connection to MSSQL requests.

- `CF-Access-Client-ID`
- `CF-Access-Client-Secret`

You'll see that the MySQL connection has been modified to include the above headers in [driver/mysql/index.js](https://github.com/brettscott/cloudflare-worker-tunnel-mysql-example/blob/main/src/driver/mysql/index.js#L3155-L3166) and [workers-override.ts](https://github.com/brettscott/cloudflare-worker-tunnel-mysql-example/blob/main/src/deno/workers-override.ts#L161-L162).

The values are passed into `connect()` within [index.ts](https://github.com/brettscott/cloudflare-worker-tunnel-mysql-example/blob/main/src/index.ts#L15).  This is the moment the MySQL server connection is established.   

Should be pretty straight-forward.
