### ISSUE TITLE
Intermittent "Failed to create WebSocket connection: 502 Bad Gateway" error

### ISSUE THREAD

**Issue by philipbattle** [brettscott/cloudflare-worker-tunnel-mysql-example#4]
This project has been a life-saver helping to run MySQL queries from a Worker.

One issue causing some pain is intermittent "Failed to create WebSocket connection: 502 Bad Gateway" errors.

Debug logging cloudflared shows absolutely nothing when this error is thrown. Around half the requests do not make it this far.

The UFW on the Ubuntu server is disabled to rule that out.

Cloudflare Trace does however show all requests making it through the various stages (i.e WAF) to the worker.

The intermittent 502 throws regardless of whether the tunnel is fronted by the recommended Cloudflare Application i.e 

Searching around, others with this error fix it by turning on "No TLS Verify", but that's only for HTTPS Public hostnames while the instructions here say to use TCP.

Perhaps you have some idea where to look to solve this problem? Am at a loss so far.

![worker-log](https://github.com/user-attachments/assets/f502eadb-11a5-49f1-8747-8ec28e6708e4)

**Comment by brettscott** [comment]
@philipbattle intermittent issues are difficult to isolate.  From my own experience, it's likely a misconfigured load balancer or the tunnel being closed after a time threshold.

Have you seen the same intermittent experience in more than one environment?  Are you able to replicate in a development or staging environment?  This will help isolate the issue.

Beyond the Unix box running MySQL, what does the rest of your network architecture look like?  How is the Unix box connected to the Internet?

How intermittent is "intermittent"?  Every minute, 6 hours?

**Comment by philipbattle** [comment]
@brettscott many thanks for the quick response. Much appreciated.

The intermittent errors occur using miniflare as well as from the deployed worker. There is no staging env as yet.

MySql is currently sitting on a Linode VPS alongside a remotely-managed instance of cloudflared.

Intermittent in this case means every few requests. Hitting the refresh button a few times will connect and then fail to connect.

Here are the Live logs from the Connector diagnostics showing both successes and errors back to back.

When an error is thrown, there are no logs from cloudflared and tcpdump on the loopback adapter shows nothing either.

![connection-live-logs](https://github.com/user-attachments/assets/bc2f5e38-c20e-4295-9a5e-fd5313baa9f0)

**Comment by brettscott** [comment]
@philipbattle thanks for the extra info.  I’ve successfully used a Linode VPS Ubuntu box running MySQL, with Cloudflared, in a production environment.   Given that, I’d rule out Linode as being the issue. 

Given it’s a Bad Gateway, and intermittent, perhaps it’s a concurrency issue - that is, how many simultaneous requests can you make to MySQL or Cloudflared. 

Let’s think about that…..

Are you using standard 3306 port?  You’re not using any DB proxying layer between MySQL and Cloudflared that is there to spread requests across DBs (or any such things). 

Could your Docker be throttling the number of connections you can make. Has the container got enough CPU and memory?   What do the container logs say? 
 
Assuming for a minute that your request is making its way through to MySQL, does MySQL metrics give you any indication of high CPU, max connections etc.

**Comment by philipbattle** [comment]
@brettscott It's a routing issue it seems. It did look like a concurrency issue, and so just to be sure the DB was migrated onto a suitably sized server from a nano node, but this did not help.  Docker is not used, and neither is there any load balancing or proxying layer in play.

While almost randomly making changes to provoke a solution, the URL for the TCP service type on the Public Hostname Page was updated to point to the Linode server's eth0 inet addr rather than the loopback Interface.

This has fixed the Intermittent error, although as a consequence MySQL needed its binding and grants loosened to allow connections other than just the localhost. This isn't ideal, and it doesn't explain why using the loopback interface causes these Intermittent errors.

![public-hostname-page](https://github.com/user-attachments/assets/645e6943-dc15-469c-adc9-762619663b0d)

**Comment by brettscott** [comment]
@philipbattle Great work isolating the issue further.

Does this mean that you've opened port 3306 on eth0 to the public?

If so, then there's no use using the tunnel and have Cloudflare communicate directly to your Linode box via the public DNS/IP on eth0.  I would not recommend this because a brute-force attack could give access to your DB.

If not, please tell me more :) 

I wonder what the issue is with Cloudflared on loopback.  Did you try both 127.0.0.1 and localhost?

**Comment by philipbattle** [comment]
@brettscott It did mean that port 3306 was open, but once the fault was narrowed down to routing, it didn't take long to identify the root cause and correctly configure the tunnel again.

The database server was cloned, and the original box had _cloudflared_ running with the same token. I guess if the tunnel has two endpoints with the same token then the request can travel down either. It doesn't seem to be load balancing, rather more like first come first served.

Well, glad it's sorted and many thanks for all your help. For anyone scrolling to the bottom for an answer...

> Ensure your _cloudflared_ instance is unique i.e. you're not running two or more with the same token.
